name: Build Linux AppImage and Create Release

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ninja build
        run: apt install ninja-build
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.5'
          channel: 'stable' # or: 'beta' or 'dev'
      - name: Install dependencies
        run: flutter pub get
      - name: Build Linux AppImage
        run: flutter build linux --release
      - uses: actions/upload-artifact@v3
        with:
          name: wine_manager.AppImage
          path: build/linux/release/bundle/flutter_project-x64.AppImage
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/linux/release/bundle/*"
          tag: v1.0.0-${{ github.run_number }}